# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e6ed9038bd67b722db3eebcc6131065ce0277f5c7510c79d68f844fea36f1565d9c8d2afce4fed3466e097e19e2e1fd054bfe6a80acf3007c7831374ba1880ff

test:
  secret_key_base: 33b5781eb0aa2fbcf0ae0050c3e6f73d8db5fe87505a85aac3e179b175682e640d05a904ca6fb59808a8caf4d07b36245f72aa03fa4f457a64a1507dd661adc6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
